WebsitePerfomance/WebsitePerfomance/Models/PageSpeedViewModel.cs
namespace WebsitePerfomance.Models
{
    public class PageSpeedViewModel
    {
        public int Id { get; set; }
        public double Speed { get; set; }
        public int IdTestingPageViewModel { get; set; }
        public TestingPageViewModel Page { get; set; }
    }
}

WebsitePerfomance/WebsitePerfomance/Models/SitePostModel.cs
namespace WebsitePerfomance.Models
{
    public class SitePostModel
    {
        public string Url { get; set; }
    }
}

WebsitePerfomance/WebsitePerfomance/Models/SiteViewModel.cs
using System.Collections.Generic;
using System.Web.Mvc;

namespace WebsitePerfomance.Models
{
    public class SiteViewModel
    {
        public SiteViewModel()
        {
            Pages = new List<TestingPageViewModel>();
            XPagesUrl = new List<string>();
            YPageSpeed = new List<double>();
        }
        public int Id { get; set; }
        public string Url { get; set; }
        public string Sitemap { get; set; }
        public double CurrentSpeedResponse { get; set; }
        public int SelectedId { get; set; }
        public List<string> XPagesUrl { get; set; }
        public List<double> YPageSpeed { get; set; }
        public IEnumerable<SelectListItem> Sites { get; set; }
        public List<TestingPageViewModel> Pages { get; set; }        

    }
}

WebsitePerfomance/WebsitePerfomance/Models/TestingPageViewModel.cs
using System;
using System.Collections.Generic;

namespace WebsitePerfomance.Models
{
    public class TestingPageViewModel
    {
        public TestingPageViewModel()
        {
            Speeds = new List<PageSpeedViewModel>();
        }
        public int Id { get; set; }
        public string PageUrl { get; set; }
        public DateTime Date { get; set; }
        public double CurrentResponseTime { get; set; }
        public int IdSite { get; set; }
        public SiteViewModel Site { get; set; }
        public double MinResponseTime { get; set; }
        public double MaxResponseTime { get; set; }
        public List<PageSpeedViewModel> Speeds { get; set; }
    }
}

WebsitePerfomance/WebsitePerfomance/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebsitePerfomance.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebsitePerfomance/WebsitePerfomance/Controllers/WebsitePerfomanceController.cs
using AutoMapper;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WebsitePerfomance.Models;
using WebsitePerfomanceManager.Business.Interfaces;
using WebsitePerfomanceManager.Business.Models;

namespace WebsitePerfomance.Controllers
{
    public class WebsitePerfomanceController : Controller
    {
        private readonly ISiteService _siteService;
        private readonly IMapper _mapper;

        public WebsitePerfomanceController(ISiteService siteService, IMapper mapper)
        {
            _siteService = siteService;
            _mapper = mapper;
        }


        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Measure(SitePostModel site)
        {
            if (site.Url != null)
            {
                var siteModel = _mapper.Map<SiteModel>(site);
                var measures = new List<TestingPageModel>();

                var checkSite = _siteService.GetSiteByUrl(site.Url); 

                if (checkSite == null)
                {
                    siteModel.Sitemap = _siteService.GetSitemap(site.Url);
                    measures = _siteService.MeasureSpeedResponse(siteModel.Sitemap);

                    if (measures == null)
                    {
                        return View("SiteMapNotFound");
                    }

                    siteModel.Pages = measures;
                    siteModel.Pages = _siteService.GetMinMax(siteModel.Pages);
                    _siteService.Add(siteModel);
                }

                else
                {
                    measures = _siteService.MeasureSpeedResponse(checkSite.Sitemap);
                    checkSite.Pages = _siteService.GetListSpeeds(measures, checkSite.Pages);
                    checkSite.Pages = _siteService.GetMinMax(checkSite.Pages);
                    _siteService.UpdateSite(checkSite.Pages, checkSite.Id);
                }

                var getSiteResult = _siteService.GetSiteByUrl(site.Url);
                var result = _mapper.Map<SiteViewModel>(getSiteResult);

                result.Pages = result.Pages.OrderBy(m => m.CurrentResponseTime).ToList();

                foreach (var item in getSiteResult.Pages)
                {
                    result.XPagesUrl.Add(item.PageUrl);
                    result.YPageSpeed.Add(item.CurrentResponseTime);
                }

                result.Sites = GetSelectList();
                               
                return View(result);
            }

            return View("Index");
        }

        public ActionResult TablePartial()
        {
            return PartialView();
        }

        public ActionResult ChartPartial()
        {         
            return PartialView();
        }

        public ActionResult Details(int SelectedId)
        {
            var site = _siteService.GetSiteById(SelectedId);
            var siteViewModel = _mapper.Map<SiteViewModel>(site);

            return View(siteViewModel);
        }

        private IEnumerable<SelectListItem> GetSelectList()
        {
            var sites = _siteService.GetAll();
            var sitesViewModel = _mapper.Map<IList<SiteViewModel>>(sites);

            var selectList = from item in sitesViewModel
                             select new SelectListItem { Text = item.Url, Value = item.Id.ToString() };

            return selectList;
        }

        public ActionResult SiteMapNotFound()
        {
            return View();
        }

        public ActionResult HistoryPartial()
        {
            return PartialView();
        }               
    }
}

WebsitePerfomance/WebsitePerfomance/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebsitePerfomance/WebsitePerfomance/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebsitePerfomance/WebsitePerfomance/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WebsitePerfomance/WebsitePerfomance/Views/Shared/ChartPartial.cshtml
@model WebsitePerfomance.Models.SiteViewModel

@{ 
    var pagesSerialize = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model.XPagesUrl));
	var speedsSerialize = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model.YPageSpeed));
}
 

<!DOCTYPE html>
<html>
<head>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js">
	</script>
</head>
<body>

	<canvas id="myChart" width="900" height="400"></canvas>
	<script type="text/javascript">

		var ctx = document.getElementById("myChart");
		var myChart = new Chart(ctx, {
			type: 'line',
			data: {
				labels: @pagesSerialize,
				datasets: [
					{
						label: 'Speeds',
						data: @speedsSerialize,
						backgroundColor: ['rgba(255, 99, 132, 0.2)',
							'rgba(54, 162, 235, 0.2)',
							'rgba(255, 206, 86, 0.2)',
							'rgba(75, 192, 192, 0.2)',
							'rgba(153, 102, 255, 0.2)',
							'rgba(255, 159, 64, 0.2)'
						],

						borderColor: [
							'rgba(255,99,132,1)',
							'rgba(54, 162, 235, 1)',
							'rgba(255, 206, 86, 1)',
							'rgba(75, 192, 192, 1)',
							'rgba(153, 102, 255, 1)',
							'rgba(255, 159, 64, 1)'
						],
						borderWidth: 1
					}
				]
			},
			options: {
				scales: {
					yAxes: [{
						ticks: {
							beginAtZero: true
						}
					}]
				}
			}
		});

	</script>
</body>
</html>

WebsitePerfomance/WebsitePerfomance/Views/Shared/HistoryPartial.cshtml
@model WebsitePerfomance.Models.SiteViewModel

<div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    PageUrl
                </th>
                <th>
                    CurrentSpeed
                </th>
                <th>
                    MinSpeed
                </th>
                <th>
                    MaxSpeed
                </th>
                <th>
                    All values
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var page in Model.Pages)
            {
            <tr>
                <td>
                    @page.PageUrl
                </td>
                <td>
                    @if (page.CurrentResponseTime == 0)
                    {
                        <h6>page was not found</h6>
                    }
                    else
                    {
                        @page.CurrentResponseTime
                    }
                </td>
                <td>
                    @page.MinResponseTime
                </td>
                <td>
                    @page.MaxResponseTime
                </td>
                <td>
                    @foreach(var speed in page.Speeds)
                    {
                    <p>@speed.Speed</p> 
                    }
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

WebsitePerfomance/WebsitePerfomance/Views/Shared/TablePartial.cshtml
@model WebsitePerfomance.Models.SiteViewModel


<div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    PageUrl
                </th>
                <th>
                    CurrentSpeed
                </th>
                <th>
                    MinSpeed
                </th>
                <th>
                    MaxSpeed
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var page in Model.Pages)
            {
            <tr>
                <td>
                    @page.PageUrl
                </td>
                <td>
                    @if (page.CurrentResponseTime == 0)
                    {
                        <h6>page was not found</h6>
                    }
                    else
                    {
                        @page.CurrentResponseTime
                    }
                </td>
                <td>
                    @page.MinResponseTime
                </td>
                <td>
                    @page.MaxResponseTime
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

WebsitePerfomance/WebsitePerfomance/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Main page", "Index", "WebsitePerfomance", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebsitePerfomance/WebsitePerfomance/Views/WebsitePerfomance/ChartArrayBasic.cshtml
@model WebsitePerfomance.Models.ChartStatisticsViewModel
@{
    ViewBag.Title = "ChartArrayBasic";
}

<h2>ChartArrayBasic</h2>

@*@Model.Chart.Write();*@

WebsitePerfomance/WebsitePerfomance/Views/WebsitePerfomance/Details.cshtml
@model WebsitePerfomance.Models.SiteViewModel
@{
    ViewBag.Title = "Details";
}
<a href="/WebsitePerfomance/Index">Back to main page</a>
<h2>Details of @Model.Url</h2>

@*@Html.Partial("ChartPartial")*@
@Html.Partial("HistoryPartial")

<a href="/WebsitePerfomance/Index">Back to main page</a>

WebsitePerfomance/WebsitePerfomance/Views/WebsitePerfomance/Index.cshtml
@model WebsitePerfomance.Models.SitePostModel
@{
    ViewBag.Title = "Index";
}

<h2>Input URL</h2>

@using (Html.BeginForm("Measure", "WebsitePerfomance", FormMethod.Post))
{
    <lable>URL</lable>
    <p>
        <input type="text" name="URL" />
    </p>

    <button type="submit" value="action">Measure response time </button>
}

WebsitePerfomance/WebsitePerfomance/Views/WebsitePerfomance/Measure.cshtml
@model WebsitePerfomance.Models.SiteViewModel
@{
    ViewBag.Title = "Measure";
}


<h3>History</h3>
@using (Html.BeginForm("Details", "WebsitePerfomance", FormMethod.Get))
{
    @Html.DropDownListFor(m => m.SelectedId, Model.Sites)
    <input type="submit" value="Details" class="btn btn-default" />
}


@Html.Partial("ChartPartial")

<h2>Input URL</h2>

@using (Html.BeginForm("Measure", "WebsitePerfomance", FormMethod.Post))
{
    <lable>URL</lable>
    <p>
        <input type="text" name="URL" />
    </p>

    <button type="submit" value="action">Measure response time </button>
}

@Html.Partial("TablePartial")

WebsitePerfomance/WebsitePerfomance/Views/WebsitePerfomance/SiteMapNotFound.cshtml
@{
    ViewBag.Title = "SiteMapNotFound";
}


    <h2>Sitemap not found, server not responding. Try another website</h2>


    <a href="/WebsitePerfomance/Index">Back to main page</a>